topic:- MinMaxScaler, Normalization

## Feature Scalling in scikit-Learn , MinMaxScaler, Normalization

In [2]:
import pandas as pd
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
df = df[['selling_price','km_driven','year']]
print(df.head())

   selling_price  km_driven  year
0          60000      70000  2007
1         135000      50000  2007
2         600000     100000  2012
3         250000      46000  2017
4         450000     141000  2014


## Feature Scaling
### TYPES- 1. Normalization   2. Standardization


 1. Normalizaton:-
 Normalization is a scaling technique in which values are shifted and rescaled 
 so that they end up ranging between 0 and 1. It is also known as Min_Max scaling

 x(scaled) = (x - x(min))/(x(max) - x(min))


# Applying Normalization: Minmax Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_df = scaler.fit_transform(df)   # it return a numpy array
print(scaled_df)


[[0.0045045  0.08678301 0.53571429]
 [0.01295045 0.06198751 0.53571429]
 [0.06531532 0.12397626 0.71428571]
 ...
 [0.01013514 0.10290008 0.60714286]
 [0.09515766 0.11157851 0.85714286]
 [0.02308559 0.04958976 0.85714286]]


In [8]:
scaled_df = pd.DataFrame(data = scaled_df,columns=df.columns)
print(scaled_df)

      selling_price  km_driven      year
0          0.004505   0.086783  0.535714
1          0.012950   0.061988  0.535714
2          0.065315   0.123976  0.714286
3          0.025901   0.057028  0.892857
4          0.048423   0.174807  0.785714
...             ...        ...       ...
4335       0.043919   0.099181  0.785714
4336       0.043919   0.099181  0.785714
4337       0.010135   0.102900  0.607143
4338       0.095158   0.111579  0.857143
4339       0.023086   0.049590  0.857143

[4340 rows x 3 columns]


# Train Test Split

In [10]:
from sklearn.model_selection import train_test_split
x = df.drop('selling_price', axis=1)
y = df['selling_price']
print(y)

0        60000
1       135000
2       600000
3       250000
4       450000
         ...  
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64


In [12]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)
# print(x_train)

# Feature-Scaling: Normalization: Minmax Scaler

In [16]:
x_train_scalled = scaler.fit_transform(x_train)
x_test_scalled = scaler.transform(x_test)

print(x_train_scalled)  # 80% scalled

[[0.02479426 0.89285714]
 [0.06198751 0.92857143]
 [0.03099313 0.75      ]
 ...
 [0.06322728 0.85714286]
 [0.09918076 0.75      ]
 [0.09918076 0.75      ]]


In [17]:
print(x_test_scalled)  # 20% scalled

[[0.09918076 0.64285714]
 [0.03347268 0.96428571]
 [0.05172589 0.57142857]
 ...
 [0.04958976 0.67857143]
 [0.0080325  0.89285714]
 [0.03719201 0.96428571]]


In [21]:
x_train_scalled = pd.DataFrame(data=x_train_scalled, columns=x_train.columns)
x_test_scalled = pd.DataFrame(data=x_test_scalled, columns=x_train.columns)

print(x_test_scalled)
# print(x_train_scalled)

     km_driven      year
0     0.099181  0.642857
1     0.033473  0.964286
2     0.051726  0.571429
3     0.174807  0.785714
4     0.074385  0.857143
..         ...       ...
863   0.074385  0.535714
864   0.148772  0.821429
865   0.049590  0.678571
866   0.008033  0.892857
867   0.037192  0.964286

[868 rows x 2 columns]
