topic:-label encoder, ordinal encoder

# Lable Encoder and Ordinal Encoder

## USING NORMAL WAY

In [35]:
import numpy as np
import pandas as pd

In [36]:
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv", usecols=['name','fuel','seller_type','transmission','owner'])

In [37]:
print(df.head())

                       name    fuel seller_type transmission         owner
0             Maruti 800 AC  Petrol  Individual       Manual   First Owner
1  Maruti Wagon R LXI Minor  Petrol  Individual       Manual   First Owner
2      Hyundai Verna 1.6 SX  Diesel  Individual       Manual   First Owner
3    Datsun RediGO T Option  Petrol  Individual       Manual   First Owner
4     Honda Amaze VX i-DTEC  Diesel  Individual       Manual  Second Owner


In [38]:
df.drop('name',axis=1, inplace=True)
df['transmission'] = df['transmission'].map({'Manual':0, 'Automatic':1})

In [39]:
print(df.head())

     fuel seller_type  transmission         owner
0  Petrol  Individual             0   First Owner
1  Petrol  Individual             0   First Owner
2  Diesel  Individual             0   First Owner
3  Petrol  Individual             0   First Owner
4  Diesel  Individual             0  Second Owner


### seller_type:- kitne alag alag seller type hain wo find krne ke liye value_counts() ka use krte hain

In [40]:
df['seller_type'].value_counts()

seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

In [41]:
df['seller_type'] = df['seller_type'].map({'Individual':0, 'Dealer':1,'Trustmark Dealer':2})

In [42]:
print(df.sample(5))

        fuel  seller_type  transmission         owner
3997  Diesel            0             0   Third Owner
711   Diesel            1             1   First Owner
1452  Diesel            0             0  Second Owner
2502  Petrol            0             0   First Owner
3513  Petrol            0             0   First Owner


In [44]:
from sklearn.model_selection import train_test_split
X = df.drop('fuel', axis=1)
y =df['fuel']

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
print(y_train)

227     Diesel
964     Diesel
2045    Petrol
1025    Diesel
4242    Diesel
         ...  
3444    Diesel
466     Diesel
3092    Diesel
3772    Diesel
860     Petrol
Name: fuel, Length: 3472, dtype: object


# Using Scikitlearn
### 1. Applying Label Encoder          2. OrdinalEncoder

LabelEncoder:- ye hmesha target value pr use hota hai mtlb output pr

In [50]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [51]:
#APPLYING LABEL ENCODER
le = LabelEncoder()

In [53]:
y_train_scaled = le.fit_transform(y_train)
y_test_scaled = le.transform(y_test)

In [57]:
print(y_train_scaled)

[1 1 4 ... 1 1 4]


In [55]:
oe = OrdinalEncoder()
X_train_traf = oe.fit_transform(X_train)
X_test_traf = oe.transform(X_test)

In [60]:
print(X_train.head(3))

      seller_type  transmission         owner
227             0             0   First Owner
964             0             0   First Owner
2045            0             0  Second Owner


In [63]:
print(X_train_traf)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 2.]
 ...
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
